### ISSUE TITLE
A button (left mouse click) sometimes minimizes game

### ISSUE THREAD

**Issue by austinarchibald** [erfg12/Blizzard_Controller_Support#5]
Hi, great tool, this is better than creating my own Steam layout. Tested on StarCraft Remastered and WC3. However, sometimes the A button (left mouse click) will minimize or switch my focused app (or shows desktop). Then I need to alt tab back to SC or WC3. Any ideas? Happened about 3 times in 10 minutes. Happened in both games. 

Also, I see the button grid overlay for SC but not WC3. Is there one for WC3? 

Thanks!

**Comment by erfg12** [comment]
Let me know if this newer version fixes the issue.
